const { Op } = require('sequelize');
const { RMSTariff } = require('../models');
const { successResponse, errorResponse, getPagination, getPaginationMeta } = require('../utils/helpers');

const withTotals = (record) => ({ ...record.toJSON(), lumpSum: record.totals() });

exports.getAll = async (req, res, next) => {
  try {
    const { page, limit, offset } = getPagination(req.query);
    const { service, trade, cargoType, search } = req.query;

    const where = {};
    if (service) where.service = service;
    if (trade) where.trade = trade;
    if (cargoType) where.cargoType = cargoType;
    if (search) {
      where[Op.or] = [
        { tariffNumber: { [Op.like]: `%${search}%` } },
        { originCountry: { [Op.like]: `%${search}%` } },
        { originPort: { [Op.like]: `%${search}%` } },
        { destinationCountry: { [Op.like]: `%${search}%` } },
        { destinationPort: { [Op.like]: `%${search}%` } },
      ];
    }

    const { count, rows } = await RMSTariff.findAndCountAll({
      where, order: [['tariffDate', 'ASC'], ['tariffNumber', 'ASC']], limit, offset,
    });
    return successResponse(res, rows, 'Tariffs retrieved', 200, getPaginationMeta(count, page, limit));
  } catch (error) {
    next(error);
  }
};

exports.getById = async (req, res, next) => {
  try {
    const record = await RMSTariff.findByPk(req.params.id);
    if (!record) return errorResponse(res, 'Tariff not found', 404);
    return successResponse(res, withTotals(record), 'Tariff retrieved');
  } catch (error) {
    next(error);
  }
};

exports.create = async (req, res, next) => {
  try {
    const record = await RMSTariff.create({ ...req.body, createdBy: req.user?.id || null });
    return successResponse(res, withTotals(record), 'Tariff created', 201);
  } catch (error) {
    next(error);
  }
};

exports.update = async (req, res, next) => {
  try {
    const record = await RMSTariff.findByPk(req.params.id);
    if (!record) return errorResponse(res, 'Tariff not found', 404);
    await record.update(req.body);
    return successResponse(res, withTotals(record), 'Tariff updated');
  } catch (error) {
    next(error);
  }
};

// Action ▸ Duplicate — copies everything except the number, which is reissued,
// and starts the copy's chatter fresh.
exports.duplicate = async (req, res, next) => {
  try {
    const source = await RMSTariff.findByPk(req.params.id);
    if (!source) return errorResponse(res, 'Tariff not found', 404);

    const { id, tariffNumber, createdAt, updatedAt, activityLog, ...rest } = source.toJSON();
    const copy = await RMSTariff.create({
      ...rest,
      tariffNumber: undefined, // regenerated by the model hook
      createdBy: req.user?.id || null,
      activityLog: [{
        at: new Date().toISOString(),
        author: req.user?.name || req.user?.email || 'System',
        kind: 'log',
        body: `Duplicated from ${tariffNumber}`,
        changes: [],
      }],
    });
    return successResponse(res, withTotals(copy), 'Tariff duplicated', 201);
  } catch (error) {
    next(error);
  }
};

exports.remove = async (req, res, next) => {
  try {
    const record = await RMSTariff.findByPk(req.params.id);
    if (!record) return errorResponse(res, 'Tariff not found', 404);
    await record.destroy();
    return successResponse(res, null, 'Tariff deleted');
  } catch (error) {
    next(error);
  }
};

exports.addActivity = async (req, res, next) => {
  try {
    const record = await RMSTariff.findByPk(req.params.id);
    if (!record) return errorResponse(res, 'Tariff not found', 404);
    const entry = {
      at: new Date().toISOString(),
      author: req.user?.name || req.user?.email || 'System',
      kind: req.body.kind || 'message',
      body: req.body.body || '',
      changes: [],
    };
    await record.update({ activityLog: [entry, ...(record.activityLog || [])] });
    return successResponse(res, entry, 'Activity logged', 201);
  } catch (error) {
    next(error);
  }
};

// Import RMS — accepts parsed rows from the uploaded spreadsheet and upserts
// them by tariff number.
exports.importTariffs = async (req, res, next) => {
  try {
    const rows = Array.isArray(req.body.rows) ? req.body.rows : [];
    if (!rows.length) return errorResponse(res, 'No rows to import', 400);

    let created = 0;
    let updated = 0;
    for (const row of rows) {
      if (!row.tariffNumber) continue;
      const existing = await RMSTariff.findOne({ where: { tariffNumber: row.tariffNumber } });
      if (existing) { await existing.update(row); updated += 1; } else { await RMSTariff.create(row); created += 1; }
    }
    return successResponse(res, { created, updated, total: rows.length }, 'Import complete');
  } catch (error) {
    next(error);
  }
};
