// "Administration > Freight Masters > Event Type" - dedicated list + detail
// records, mirroring CargoFlo ERP's "Event Type" screen (Event Code / Event
// Name columns, Create button, and a detail/edit view with Event Name /
// Event Code / Public Visible toggle and a Summary tab).
export const EVENT_TYPES = [
  { code: 'BR', name: 'BOOKING RECEIVED', publicVisible: true, summary: 'Package arrived at destination' },
  { code: 'ETD', name: 'ETD', publicVisible: true, summary: '' },
  { code: 'TR', name: 'TRANSPORTATION (CARGO MOVED FROM SHIPPER FACTORY TO CFS)', publicVisible: true, summary: '' },
  { code: 'SB', name: 'SHIPPING BILL (DOCS RECEIVED AT CFS)', publicVisible: true, summary: '' },
  { code: 'CT', name: 'CARTING (CARGO RECEIVED AT CFS)', publicVisible: true, summary: '' },
  { code: 'COC', name: 'CARGO OUT OF CHARGES', publicVisible: true, summary: '' },
  { code: 'SD', name: 'STUFFING DATE', publicVisible: true, summary: '' },
  { code: 'GID', name: 'GATE IN DATE', publicVisible: true, summary: '' },
  { code: 'SI', name: 'SI SUBMISSION', publicVisible: true, summary: '' },
  { code: 'CCNF', name: 'Customer order Confirmed', publicVisible: true, summary: '' },
  { code: 'BKD', name: 'Booked (Pieces: 1 | Weight: 218.70)', publicVisible: true, summary: '' },
  { code: 'RCF', name: 'Received from Flight (Pieces: 1 | Weight: 218.70)', publicVisible: true, summary: '' },
  { code: '1223', name: 'port delays', publicVisible: true, summary: '' },
  { code: 'DLV', name: 'Delivered (Pieces: 1 | Weight: 218.70)', publicVisible: true, summary: '' },
  { code: 'dischargeFromVessel', name: 'Discharge from Vessel', publicVisible: true, summary: '' },
  { code: 'loadOnVessel', name: 'Load on Vessel', publicVisible: true, summary: '' },
  { code: 'DEP', name: 'Flight Departure (Pieces: 1 | Weight: 218.70)', publicVisible: true, summary: '' },
  { code: 'CLC', name: 'CustomsClearance (Pieces: 7 | Weight: 1.00)', publicVisible: true, summary: '' },
  { code: 'NAN', name: 'Ready to board aircraft (Pieces: 7 | Weight: 1.00)', publicVisible: true, summary: '' },
  { code: 'MAN', name: 'Manifested (Pieces: 1 | Weight: 218.70)', publicVisible: true, summary: '' },
  { code: 'ARR', name: 'Flight Arrival (Pieces: 7 | Weight: 1.00)', publicVisible: true, summary: '' },
  { code: 'AWD', name: 'Arrival Documents delivered to Consignee (Pieces: 7 | Weight: 1.00)', publicVisible: true, summary: '' },
  { code: 'loadOnRail', name: 'Load on Rail', publicVisible: true, summary: '' },
  { code: 'railDepartureWithContainer', name: 'Rail Departure', publicVisible: true, summary: '' },
  { code: 'railArrivalWithcontainer', name: 'Rail Arrival', publicVisible: true, summary: '' },
  { code: 'dischargeFromRail', name: 'Discharge from Rail', publicVisible: true, summary: '' },
  { code: 'gateInWithContainerEmpty', name: 'Empty Container Gate In', publicVisible: true, summary: '' },
  { code: 'AR Invoice Created', name: 'AR Invoice Created (AR Invoice Created)', publicVisible: true, summary: '' },
  { code: 'ARVBRG', name: 'ARVBRG (Arrived by Barge)', publicVisible: true, summary: '' },
  { code: 'ARVDEST', name: 'ARVDEST (Arrived at Destination Port)', publicVisible: true, summary: '' },
  { code: 'vesselArrivalWithContainer', name: 'Vessel Arrival', publicVisible: true, summary: '' },
  { code: 'PFD', name: 'Pre-Manifested (Pieces: 7 | Weight: 1.00)', publicVisible: true, summary: '' },
  { code: 'BRTHTRN', name: 'BRTHTRN (Berthing at Transhipment Port)', publicVisible: true, summary: '' },
  { code: 'BRTHDEST', name: 'BRTHDEST (Berthing at Destination Port)', publicVisible: true, summary: '' },
  { code: 'FOH', name: 'Freight on Hand (Pieces: 7 | Weight: 1.00)', publicVisible: true, summary: '' },
  { code: 'RCS', name: 'Received from Shipper (Pieces: 1 | Weight: 218.70)', publicVisible: true, summary: '' },
  { code: 'CAROWUS', name: 'CAROWUS (Carrier Own Use)', publicVisible: true, summary: '' },
  { code: 'CARREL', name: 'CARREL (Carrier Release)', publicVisible: true, summary: '' },
  { code: 'CFG', name: 'CFG (Order Events)', publicVisible: true, summary: '' },
  { code: 'CNPKUPTK', name: 'CNPKUPTK (Container Picked up by Truck)', publicVisible: true, summary: '' },
  { code: 'CNRECCAR', name: 'CNRECCAR (Container Received by Carrier)', publicVisible: true, summary: '' },
  { code: 'CNRETCAR', name: 'CNRETCAR (Container Returned to Carrier)', publicVisible: true, summary: '' },
  { code: 'CNTNOASN', name: 'CNTNOASN (Container Number Assigned)', publicVisible: true, summary: '' },
  { code: 'CNTRN', name: 'CNTRN (Container in Transit)', publicVisible: true, summary: '' },
  { code: 'CNTRNS', name: 'CNTRNS (Container Transferred)', publicVisible: true, summary: '' },
  { code: 'CRGARVCFS', name: 'CRGARVCFS (Cargo Arrived at CFS)', publicVisible: true, summary: '' },
  { code: 'CRGARVWH', name: 'CRGARVWH (Cargo Arrived at Warehouse)', publicVisible: true, summary: '' },
  { code: 'CRGDLV', name: 'CRGDLV (Cargo Delivered)', publicVisible: true, summary: '' },
  { code: 'CUSREL', name: 'CUSREL (Customs Release)', publicVisible: true, summary: '' },
  { code: 'DPRBRG', name: 'DPRBRG (Departed by Barge)', publicVisible: true, summary: '' },
  { code: 'DPRORG', name: 'DPRORG (Departed from Origin Port)', publicVisible: true, summary: '' },
  { code: 'DPRRL', name: 'DPRRL (Departed by Rail)', publicVisible: true, summary: '' },
  { code: 'DPRTK', name: 'DPRTK (Departed by Truck)', publicVisible: true, summary: '' },
  { code: 'DPRTRN', name: 'DPRTRN (Departed from Transhipment Port)', publicVisible: true, summary: '' },
  { code: 'DSGBRG', name: 'DSGBRG (Discharged From Barge)', publicVisible: true, summary: '' },
  { code: 'DSGRL', name: 'DSGRL (Discharged From Rail)', publicVisible: true, summary: '' },
  { code: 'DSGVS', name: 'DSGVS (Discharged From Vessel)', publicVisible: true, summary: '' },
  { code: 'DSGVSTRN', name: 'DSGVSTRN (Discharged from Vessel at Transhipment Port)', publicVisible: true, summary: '' },
  { code: 'EMPCNDLV', name: 'EMPCNDLV (Empty Container Delivered)', publicVisible: true, summary: '' },
  { code: 'EMPCNGI', name: 'EMPCNGI (Empty Container Gate In)', publicVisible: true, summary: '' },
  { code: 'EMPCNGO', name: 'EMPCNGO (Empty Container Gate Out)', publicVisible: true, summary: '' },
  { code: 'EMPCNNTH', name: 'EMPCNNTH (Empty Container Not Hired)', publicVisible: true, summary: '' },
  { code: 'BKNGCONFM', name: 'BKNGCONFM (Booking Confirmed)', publicVisible: true, summary: '' },
  { code: 'FLCNGO', name: 'FLCNGO (Full Container Gate Out)', publicVisible: true, summary: '' },
  { code: 'FLCNGI', name: 'FLCNGI (Full Container Gate In)', publicVisible: true, summary: '' },
  { code: 'ARVRLS', name: 'ARVRLS (Arrived at Rail Station)', publicVisible: true, summary: '' },
  { code: 'ARVTRN', name: 'ARVTRN (Arrived at Transhipment Port)', publicVisible: true, summary: '' },
  { code: 'gateOutWithContainerFull', name: 'Full Container Gate Out', publicVisible: true, summary: '' },
  { code: 'FLCNDLV', name: 'FLCNDLV (Full Container Delivered)', publicVisible: true, summary: '' },
  { code: 'FLCNPKU', name: 'FLCNPKU (Full Container Picked Up)', publicVisible: true, summary: '' },
  { code: 'GDFC', name: 'GDFC (Goods Dispatched from CFS)', publicVisible: true, summary: '' },
  { code: 'HBGNTD', name: 'HBGNTD (House Bill Generated)', publicVisible: true, summary: '' },
  { code: 'IMPCUSHLD', name: 'IMPCUSHLD (Import Custom Hold)', publicVisible: true, summary: '' },
  { code: 'INVGNTD', name: 'INVGNTD (Invoice Generated)', publicVisible: true, summary: '' },
  { code: 'LODBRG', name: 'LODBRG (Loaded on Barge)', publicVisible: true, summary: '' },
  { code: 'LODRL', name: 'LODRL (Loaded on Rail)', publicVisible: true, summary: '' },
  { code: 'LODVS', name: 'LODVS (Loaded on Vessel)', publicVisible: true, summary: '' },
  { code: 'RDYLOD', name: 'RDYLOD (Ready to be Loaded)', publicVisible: true, summary: '' },
  { code: 'SHPCMPLT', name: 'SHPCMPLT (Shipment is completed)', publicVisible: true, summary: '' },
  { code: 'SHPCNFRM', name: 'SHPCNFRM (Shipment is Confirmed)', publicVisible: true, summary: '' },
  { code: 'EMPCNRTN', name: 'EMPCNRTN (Empty Container Returned)', publicVisible: true, summary: '' },
];
