// Static data describing the "Companies & Users > Groups" list, matching the
// SeaRates ERP "Applications" (res.groups) view: groups organized under
// module/category headers, each with a count, e.g. "Administration (2)".

export const GROUP_CATEGORIES = [
  { name: 'Administration', groups: ['Access Rights', 'Settings'] },
  { name: 'Audit Logs', groups: ['View Audit Logs'] },
  { name: 'Contracts', groups: ['Administrator'] },
  { name: 'Customs', groups: ['Customs: Admin', 'Customs Support User', 'Customs: User'] },
  { name: 'Employees', groups: ['Administrator', 'Officer'] },
  { name: 'Events', groups: ['Administrator', 'Registration Desk', 'User'] },
  { name: 'Extra Rights', groups: ['Contact Creation', 'Multi Companies', 'Multi Currencies', 'Technical Features'] },
  { name: 'Invoicing', groups: ['Billing', 'Billing Administrator'] },
  { name: 'Live Chat', groups: ['Administrator', 'User'] },
  { name: 'Operations', groups: ['Administrator', 'Associate', 'Operation Manager'] },
  { name: 'Project', groups: ['Administrator', 'User'] },
  { name: 'Purchase', groups: ['Administrator', 'User'] },
  { name: 'Recruitment', groups: ['Administrator', 'Officer'] },
  { name: 'Sales', groups: ['Administrator', 'User: All Documents', 'User: Own Documents Only'] },
  { name: 'Sales & CRM', groups: ['Sales Administrator', 'Salesman', 'Sales Manager'] },
  { name: 'Schedule', groups: ['Schedule Administrator', 'Schedule User'] },
  { name: 'Service Job', groups: ['Super Admin'] },
  { name: 'Shipment', groups: ['Administrator', 'Super Admin', 'User: All Documents', 'User: Own Documents Only'] },
  {
    name: 'Technical',
    groups: [
      'Access to export feature',
      'Access to Private Addresses',
      'Addresses in Sales Orders',
      'Advanced Pricelists',
      'Allow the cash rounding management',
      'Analytic Accounting',
      'Analytic Accounting Tags',
      'A warning can be set on a partner (Account)',
      'A warning can be set on a product or a customer (Purchase)',
      'A warning can be set on a product or a customer (Sale)',
      'Basic Pricelists',
      'Discount on lines',
      'Lock Confirmed Sales',
      'Mail Template Editor',
      'Manage Multiple Units of Measure',
      'Manage Product Packaging',
      'Manage Product Variants',
      'Manage Reseller(E-Commerce)',
      'Multi-website',
      'Pro-forma Invoices',
      'Purchase Receipt',
      'Quotation Templates',
      'Report Scheduler Access',
      'Sale Receipt',
      'Send an automatic reminder email to confirm delivery',
      'Show Accounting Features - Readonly',
      'Show Full Accounting Features',
      'Show Lead Menu',
      'Show Recurring Revenues Menu',
      'Tax display B2B',
      'Tax display B2C',
      'Use Rating on Project',
      'Use Recurring Tasks',
      'Use Stages on Project',
      'Use Subtasks',
      'Use Task Dependencies',
    ],
  },
  { name: 'Technical Support', groups: ['Freight Technical Support Team', 'System Base: All Menu Access'] },
  { name: 'User types', groups: ['Internal User', 'Portal', 'Public'] },
  { name: 'Website', groups: ['Editor and Designer', 'Restricted Editor'] },
  { name: 'WMS', groups: ['WMS Admin', 'WMS User'] },
];

// Flat list with stable ids, used for selection / export.
export const ALL_GROUPS = GROUP_CATEGORIES.flatMap((cat) =>
  cat.groups.map((g) => ({
    id: `${cat.name} / ${g}`,
    category: cat.name,
    name: g,
    groupName: `${cat.name} / ${g}`,
  }))
);

// Representative set of fields available on the underlying "Created by" / "Last
// Updated by" (res.users) related record, used inside the Export Data modal's
// field picker, mirroring the field list exported from SeaRates ERP.
export const USER_RELATED_FIELDS = [
  '# Access Rights', '# Groups', '# Meetings', '# Record Rules', '# Tasks', '# Vendor Bills',
  'Access Token', 'Account Payable', 'Account Receivable', 'Action Needed', 'Active',
  'Active Lang Count', 'Activities', 'Activities Done Target', 'Activity Exception Decoration',
  'Activity Responsible User', 'Activity State', 'Activity Type Icon', 'Address',
  'Address Reference ID', 'Address Type', 'Allowed Companies', 'API Keys', 'App Code',
  'Approved Credit Days', 'Approved Credit Limit', 'Attachment Count', 'Avatar', 'Avatar 1024',
  'Avatar 128', 'Avatar 256', 'Avatar 512', 'Badges', 'Bank', 'Banks', 'BCC Email', 'Blacklist',
  'Bot Status', 'Bounce', 'Branch Code', 'Bronze badges count', 'Building Number', 'Buyco Token',
  'Can Edit', 'Can Publish', 'Cargo Ai Token', 'Cargo Type', 'Cargo Type Domain', 'CC Email',
  'Channels', 'City', 'City of Address', 'Coach', 'Color Index', 'Commercial Entity',
  'Companies that refers to partner', 'Company employee', 'Company Name', 'Company Name Entity',
  'Company Type', 'Complete Address', 'Contact Address Type', 'Contact Person', 'Country',
  'Country Code', 'Create Date', 'Created by', 'Credit', 'Credit Limit', 'Credit Limit Approver',
  'Credit Limits', 'Currency', 'Customer', 'Customer Code', 'Customer Code Number',
  'Customer Odoo Code', 'Customer Payment Terms', 'Customer Rank', 'Customer Reference ID',
  'Customs User Broker Details', 'Date', 'Days Before Receipt', 'Default Company',
  'Default Working Hours', 'Degree of trust you have in this debtor', 'Department',
  'Display Name', 'Door', 'Dynamic VAT Label', 'EIN NO', 'Email', 'Email Address',
  'Email Signature', 'Employee', 'Employee Count', 'Employee Lang', 'Employee Type',
  'Enable Customer KYC Feature', 'Enforce Cities', 'External ID', 'Fax', 'First Name',
  'Fiscal Position', 'Followers', 'Followers (Partners)', 'Formatted Email', 'Freight Carrier',
  'Geo Latitude', 'Geo Longitude', 'Goal', 'Gold badges count', 'Govt. Registration No.',
  'Groups', 'GST Treatment', 'Has Message', 'Has Unreconciled Entries', 'HelpDesk Token',
  'Home Action', 'House', 'Hr Presence State', 'Icon', 'ID', 'Identification Number',
  'Identification Number (SA)', 'Identification Scheme', 'Identification Type', 'IM Status',
  'Image', 'Image 1024', 'Image 128', 'Image 256', 'Image 512', 'Industry',
  'Internal Credit Limit', 'Internal Reference No.', 'Invoice', 'Invoiced in Sales Orders Target',
  'Invoices', 'Inward Strategy', 'Is a Company', 'Is Approval Authority', 'Is Back Order',
  'Is Company In India', 'Is Credit Limit Approval Authority', 'Is Customs Broker?',
  'Is Email Alert', 'Is Follower', 'Is GST Exempted', 'Is Published', 'Is SMS Alert',
  'Is System', 'Is Tech Support User', 'Job Position', 'Job Title', 'Journal Items', 'Karma',
  'Karma Changes', 'L10N Sa Company Country Code', 'Language', 'Last Activity',
  'Last Activity Time', 'Last Modified on', 'Last Name',
  'Last notification marked as read from base Calendar', 'Last Updated by', 'Last Updated on',
  'Latest authentication', 'Latest Invoices & Payments Matching Date', 'Livechat Username',
  'Localization Country Code', 'Main Attachment', 'Manager', 'Manual Address ID',
  'Mark As Default', 'Meetings', 'Message Delivery error', 'Message for Invoice',
  'Message for Purchase Order', 'Message for Sales Order', 'Messages', 'Middle Name', 'Mobile',
  'My Activity Deadline', 'Name', 'Next Activity Calendar Event', 'Next Activity Deadline',
  'Next Activity Summary', 'Next Activity Type', 'Next Rank', 'NIFNO', 'Non Credit or Cash',
  'Normalized Email', 'Notes', 'Notification', 'Number of Actions', 'Number of Companies',
  'Number of errors', 'Odoobot Failed', 'Operation Auto Email', 'Opportunities', 'Opportunity',
  'PAN No.', 'Parent name', 'Partner Contracts', 'Partner is Active',
  'Partner with same Tax ID', 'partner_kyc_document', 'Password', 'Payable Limit',
  'Payment Token Count', 'Payment Tokens', 'Phone', 'Pick Strategy', 'Plot Identification',
  'Pricelist', 'Pricelist Manually Unset', 'Private City', 'Private Country', 'Private Email',
  'Private State', 'Private Street', 'Private Street2', 'Private Zip', 'PST', 'Purchase Order',
  'Purchase Order Count', 'Rank', 'Receipt Reminder', 'Reference', 'Refresh Token',
  'Registration Type', 'Related Company', 'Related employee', 'Related Partner', 'Reports Name',
  'Res Users Settings', 'Resources', 'Sale Order Count', 'Sales Order', 'Sales Team',
  'Sales Team Members', 'Sales Teams', 'Sales Warnings', 'Salesperson', 'Self', 'Seo name',
  'SEO optimized', 'Set Password', 'Share Partner', 'Share User', 'Shipment Type',
  'Shipping GSTIN', 'Shipping Provider URL', 'Show Broker License Section', 'Show Credit Limit',
  'Signup Expiration', 'Signup Token', 'Signup Token is Valid', 'Signup Token Type',
  'Signup URL', 'Silver badges count', 'SST Registration Number', 'State', 'Status', 'Street',
  'Street Name', 'Street2', 'Supplier Currency', 'Supplier Rank', 'Tags', 'Tasks',
  'The employee address has a company linked', 'Timezone', 'Timezone offset', 'Title',
  'Total Billed', 'Total Invoiced', 'Total Payable', 'Total Receivable', 'Transaction Type',
  'Transport Mode', 'Unique Hash', 'Unread Messages', 'Unread Messages Counter',
  'User Livechat Username', 'User log entries', 'User Sales Team', 'Users',
  'Vendor Payment Terms', 'Visible on current website', 'Visitors', 'Waiting post',
  'Warehouse Code', 'Warehouse Code(s)', 'Website', 'Website Link', 'Website Messages',
  'Website meta description', 'Website meta keywords', 'Website meta title',
  'Website opengraph image', 'Website Partner Full Description',
  'Website Partner Short Description', 'Website URL', 'Won in Opportunities Target',
  'Work Address', 'Work Email', 'Work Location', 'Work Mobile', 'Work Phone', 'Zip',
];

const userRelatedChildren = () =>
  USER_RELATED_FIELDS.map((f) => ({ label: f, expandable: f === 'Created by' || f === 'Last Updated by' }));

// Field tree shown in the "Available fields" panel of the Export Data modal.
// Each node has a `label`; nodes with `expandable: true` show a ">" toggle
// that reveals `children`, while leaf nodes show a "+" to add the field to
// the export list.
export const EXPORT_FIELD_TREE = [
  {
    label: 'Access Controls',
    expandable: true,
    children: [
      { label: 'Active' },
      { label: 'Create Access' },
      { label: 'Created by', expandable: true, children: userRelatedChildren() },
      { label: 'Created on' },
      { label: 'Delete Access' },
      { label: 'Display Name' },
      { label: 'External ID' },
      { label: 'Group', expandable: true, children: [{ label: 'Name' }, { label: 'Application' }] },
      { label: 'ID' },
      { label: 'Last Modified on' },
      { label: 'Last Updated by', expandable: true, children: userRelatedChildren() },
      { label: 'Last Updated on' },
      { label: 'Model', expandable: true, children: [{ label: 'Model Name' }, { label: 'Model Description' }] },
      { label: 'Name' },
      { label: 'Read Access' },
      { label: 'Write Access' },
    ],
  },
  {
    label: 'Access Menu',
    expandable: true,
    children: [
      { label: 'Action' },
      { label: 'Active' },
      { label: 'Child IDs', expandable: true, children: [{ label: 'Name' }] },
      { label: 'Created by', expandable: true, children: userRelatedChildren() },
      { label: 'Created on' },
      { label: 'Display Name' },
      { label: 'External ID' },
      { label: 'Full Path' },
      { label: 'Groups', expandable: true, children: [{ label: 'Group Name' }] },
      { label: 'ID' },
      { label: 'Last Modified on' },
      { label: 'Last Updated by', expandable: true, children: userRelatedChildren() },
      { label: 'Last Updated on' },
      { label: 'Menu' },
      { label: 'Parent Menu', expandable: true, children: [{ label: 'Name' }] },
      { label: 'Parent Path' },
      { label: 'Sequence' },
      { label: 'Theme Menu Access Allowed' },
      { label: 'Theme Menu Icon' },
      { label: 'Web Icon File' },
      { label: 'Web Icon Image' },
    ],
  },
  {
    label: 'Application',
    expandable: true,
    children: [
      { label: 'Child Applications', expandable: true, children: [{ label: 'Name' }] },
      { label: 'Created by', expandable: true, children: userRelatedChildren() },
      { label: 'Created on' },
      { label: 'Description' },
      { label: 'Display Name' },
      { label: 'Exclusive' },
      { label: 'External ID' },
      { label: 'ID' },
      { label: 'Last Modified on' },
      { label: 'Last Updated by', expandable: true, children: userRelatedChildren() },
      { label: 'Last Updated on' },
      { label: 'Modules', expandable: true, children: [{ label: 'Module Name' }] },
      { label: 'Name' },
      { label: 'Number of Apps' },
      { label: 'Parent Application', expandable: true, children: [{ label: 'Name' }] },
      { label: 'Sequence' },
      { label: 'Visible' },
    ],
  },
  { label: 'Color Index' },
  { label: 'Comment' },
  { label: 'Created by', expandable: true, children: userRelatedChildren() },
  { label: 'Created on' },
  { label: 'Display Name' },
  { label: 'External ID' },
  { label: 'Group Name' },
  { label: 'ID' },
  {
    label: 'Inherits',
    expandable: true,
    children: [
      { label: 'Name' },
      { label: 'Application' },
      { label: 'Comment' },
      { label: 'Color Index' },
    ],
  },
  { label: 'Last Modified on' },
  { label: 'Last Updated by', expandable: true, children: userRelatedChildren() },
  { label: 'Last Updated on' },
  { label: 'Name' },
  {
    label: 'Rules',
    expandable: true,
    children: [
      { label: 'Rule Name' },
      { label: 'Active' },
      { label: 'Domain' },
      { label: 'Model' },
    ],
  },
  {
    label: 'Share Group',
    expandable: true,
    children: [
      { label: 'Name' },
      { label: 'Application' },
      { label: 'Comment' },
    ],
  },
  {
    label: 'Transitive Inherits',
    expandable: true,
    children: [
      { label: 'Name' },
      { label: 'Application' },
      { label: 'Comment' },
      { label: 'Color Index' },
    ],
  },
];
