// "Administration > Freight Masters > Package Info" - dedicated list,
// mirroring CargoFlo ERP's "Package Info" screen: Code / Kind / Type /
// Material Code / Material / Category columns, Download-only toolbar (no
// Create), a checkbox + "Action > Export" menu, and an "Export Data" dialog.
export const PACKAGE_INFOS = [
  { code: '1A1', kind: '1', type: 'Drums', materialCode: 'A', material: 'Steel', category: 'non-removable head' },
  { code: '1A2', kind: '1', type: 'Drums', materialCode: 'A', material: 'Steel', category: 'removable head' },
  { code: '1B1', kind: '1', type: 'Drums', materialCode: 'B', material: 'Aluminium', category: 'non-removable head' },
  { code: '1B2', kind: '1', type: 'Drums', materialCode: 'B', material: 'Aluminium', category: 'removable head' },
  { code: '1D', kind: '1', type: 'Drums', materialCode: 'D', material: 'Plywood', category: '' },
  { code: '1G', kind: '1', type: 'Drums', materialCode: 'G', material: 'Fibre', category: '' },
  { code: '1H1', kind: '1', type: 'Drums', materialCode: 'H', material: 'Plastics', category: 'non-removable head' },
  { code: '1H2', kind: '1', type: 'Drums', materialCode: 'H', material: 'Plastics', category: 'removable head' },
  { code: '2C1', kind: '2', type: 'Barrels', materialCode: 'C', material: 'Wooden', category: 'bung type' },
  { code: '2C2', kind: '2', type: 'Barrels', materialCode: 'C', material: 'Wooden', category: 'removable head' },
  { code: '3A1', kind: '3', type: 'Jerricans', materialCode: 'A', material: 'Steel', category: 'non-removable head' },
  { code: '3A2', kind: '3', type: 'Jerricans', materialCode: 'A', material: 'Steel', category: 'removable head' },
  { code: '3H1', kind: '3', type: 'Jerricans', materialCode: 'H', material: 'Plastics', category: 'non-removable head' },
  { code: '3H2', kind: '3', type: 'Jerricans', materialCode: 'H', material: 'Plastics', category: 'removable head' },
  { code: '4A', kind: '4', type: 'Boxes', materialCode: 'A', material: 'Steel', category: '' },
  { code: '4B', kind: '4', type: 'Boxes', materialCode: 'B', material: 'Aluminium', category: '' },
  { code: '4C1', kind: '4', type: 'Boxes', materialCode: 'C', material: 'Natural wood', category: 'ordinary' },
  { code: '4C2', kind: '4', type: 'Boxes', materialCode: 'C', material: 'Natural wood', category: 'with sift-proof walls' },
  { code: '4D', kind: '4', type: 'Boxes', materialCode: 'D', material: 'Plywood', category: '' },
  { code: '4F', kind: '4', type: 'Boxes', materialCode: 'F', material: 'Reconstituted wood', category: '' },
  { code: '4G', kind: '4', type: 'Boxes', materialCode: 'G', material: 'Fibreboard', category: '' },
  { code: '4H1', kind: '4', type: 'Boxes', materialCode: 'H', material: 'Plastics', category: 'expanded' },
  { code: '4H2', kind: '4', type: 'Boxes', materialCode: 'H', material: 'Plastics', category: 'solid' },
  { code: '5H1', kind: '5', type: 'Bags', materialCode: 'H', material: 'Woven plastics', category: 'without inner lining or coating' },
  { code: '5H2', kind: '5', type: 'Bags', materialCode: 'H', material: 'Woven plastics', category: 'silt-proof' },
  { code: '5H3', kind: '5', type: 'Bags', materialCode: 'H', material: 'Woven plastics', category: 'water resistant' },
  { code: '5H4', kind: '5', type: 'Bags', materialCode: 'H', material: 'Plastics film', category: '' },
  { code: '5L1', kind: '5', type: 'Bags', materialCode: 'L', material: 'Textile', category: 'without inner lining or coating' },
  { code: '5L2', kind: '5', type: 'Bags', materialCode: 'L', material: 'Textile', category: 'sift-proof' },
  { code: '5L3', kind: '5', type: 'Bags', materialCode: 'L', material: 'Textile', category: 'water resistant' },
  { code: '5M1', kind: '5', type: 'Bags', materialCode: 'M', material: 'Paper', category: 'multiwall' },
  { code: '5M2', kind: '5', type: 'Bags', materialCode: 'M', material: 'Paper', category: 'multiwall, water resistant' },
  { code: '6HA1', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in steel drum' },
  { code: '6HA2', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in steel crate or box' },
  { code: '6HB', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in aluminium drum' },
  { code: '6HB2', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in aluminium crate or box' },
  { code: '6HC', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'wooden box' },
  { code: '6HD1', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in plywood drum' },
  { code: '6HD2', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in plywood box' },
  { code: '6HG1', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in fibre drum' },
  { code: '6HG2', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in fibreboard box' },
  { code: '6HH1', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in plastics drum' },
  { code: '6HH2', kind: '6', type: 'Composite Packaging', materialCode: 'H', material: 'Plastics receptacle', category: 'in solid plastics box' },
  { code: '6PA1', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in steel drum' },
  { code: '6PA2', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in steel crate or box' },
  { code: '6PB1', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in aluminium drum' },
  { code: '6PB2', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in aluminium crate or box' },
  { code: '6PC', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'wooden box' },
  { code: '6PD1', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in plywood drum' },
  { code: '6PD2', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in wickerwork hamper' },
  { code: '6PG1', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in fibre drum' },
  { code: '6PG2', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in fibreboard box' },
  { code: '6PH1', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in expanded plastics packaging' },
  { code: '6PH2', kind: '6', type: 'Composite Packaging', materialCode: 'P', material: 'Glass, porcelain or stoneware receptacle', category: 'in solid plastics packaging' },
];
