// "Administration > Freight Masters > Unit of Measures" data, mirroring
// SeaRates ERP's "Units of Measure Categories" screen: each category lists
// its UoMs as chips, with the reference/active UoM highlighted.

export const UOM_CATEGORIES = [
  {
    category: 'Unit',
    uoms: [
      { code: 'Units', label: 'Units', active: true },
      { code: 'SQFT', label: 'SQFT' },
      { code: 'NOS', label: 'NOS' },
      { code: 'CARTON BOX ON PLASTIC PALLET', label: 'CARTON BOX ON PLASTIC PALLET' },
      { code: 'PZ', label: 'PZ' },
      { code: 'Box', label: 'Box' },
      { code: 'Bag', label: 'Bag' },
      { code: 'Paper', label: 'Paper' },
      { code: 'Agro', label: 'Agro' },
      { code: 'CARTON BOX ON PLASTIC', label: 'CARTON BOX ON PLASTIC' },
      { code: 'CTN', label: 'CTN' },
      { code: 'Dozens', label: 'Dozens' },
    ],
  },
  {
    category: 'Weight',
    uoms: [
      { code: 'g', label: 'g' },
      { code: 'oz', label: 'oz' },
      { code: 'lb', label: 'lb' },
      { code: 'lbs', label: 'lbs' },
      { code: 'kg', label: 'kg', active: true },
      { code: 't', label: 't' },
    ],
  },
  {
    category: 'Working Time',
    uoms: [
      { code: 'Hours', label: 'Hours' },
      { code: 'Days', label: 'Days', active: true },
    ],
  },
  {
    category: 'Length / Distance',
    uoms: [
      { code: 'mm', label: 'mm' },
      { code: 'cm', label: 'cm' },
      { code: 'in', label: 'in' },
      { code: 'ft', label: 'ft' },
      { code: 'm', label: 'm', active: true },
      { code: 'km', label: 'km' },
      { code: 'mi', label: 'mi' },
    ],
  },
  {
    category: 'Surface',
    uoms: [
      { code: 'ft2', label: 'ft²' },
      { code: 'm2', label: 'm²', active: true },
    ],
  },
  {
    category: 'Volume',
    uoms: [
      { code: 'in3', label: 'in³' },
      { code: 'fl oz (US)', label: 'fl oz (US)' },
      { code: 'qt (US)', label: 'qt (US)' },
      { code: 'L', label: 'L', active: true },
      { code: 'gal (US)', label: 'gal (US)' },
      { code: 'ft3', label: 'ft³' },
      { code: 'm3', label: 'm³' },
    ],
  },
  {
    category: 'Pack',
    uoms: [
      { code: 'BAG', label: 'BAG (Bag)' },
      { code: 'AMM', label: 'AMM (Ammo Pack)' },
      { code: 'BAL', label: 'BAL (Bale)' },
      { code: 'BBG', label: 'BBG (Bulk Bag)' },
      { code: 'BBK', label: 'BBK (Break Bulk)' },
      { code: 'BBL', label: 'BBL (Barrel)' },
      { code: 'BDL', label: 'BDL (Bundle)' },
      { code: 'BEM', label: 'BEM (Beam)' },
      { code: 'BIC', label: 'BIC (Bing Chest)' },
      { code: 'BIN', label: 'BIN (Bin)' },
      { code: 'BKG', label: 'BKG (Bulk Bag)' },
      { code: 'BKT', label: 'BKT (Bucket)' },
      { code: 'BLC', label: 'BLC (Bale, Compressed)' },
      { code: 'BLE', label: 'BLE (Bale)' },
      { code: 'BLK', label: 'BLK (Bulk)' },
      { code: 'BLU', label: 'BLU (Bale, UnCompressed)' },
      { code: 'BND', label: 'BND (Bundle)' },
      { code: 'BOB', label: 'BOB (Bobbin)' },
      { code: 'BOT', label: 'BOT (Bottle)' },
      { code: 'BOX', label: 'BOX (Box)', active: true },
      { code: 'BRG', label: 'BRG (Barge)' },
      { code: 'BSK', label: 'BSK (Basket)' },
      { code: 'BXI', label: 'BXI (Box with inner container)' },
      { code: 'BXT', label: 'BXT (Bucket)' },
      { code: 'CAB', label: 'CAB (Cabinet)' },
      { code: 'CAG', label: 'CAG (Cage)' },
      { code: 'CAN', label: 'CAN (Can)' },
      { code: 'CAR', label: 'CAR (Carcass)' },
      { code: 'CAS', label: 'CAS (Case)' },
      { code: 'CBC', label: 'CBC (Container Bulk Cargo)' },
      { code: 'CBY', label: 'CBY (Carboy)' },
      { code: 'CCS', label: 'CCS (Can Case)' },
      { code: 'CHE', label: 'CHE (Cheeses)' },
      { code: 'CHS', label: 'CHS (Chest)' },
      { code: 'CLD', label: 'CLD (Car Load, Rail)' },
      { code: 'CNA', label: 'CNA (Household goods, Containers,...)' },
      { code: 'CNB', label: 'CNB (Container MSC ISO Military ...)' },
      { code: 'CNC', label: 'CNC (Container, Navy Cargo Transp...)' },
      { code: 'CND', label: 'CND (Container, Commercial High...)' },
      { code: 'CNE', label: 'CNE (Engine Container)' },
      { code: 'CNF', label: 'CNF (Multiwall Container Secured t...)' },
      { code: 'CNT', label: 'CNT (Container)' },
      { code: 'CNX', label: 'CNX (CONEX Container Express)' },
      { code: 'COI', label: 'COI (Coil)' },
      { code: 'COL', label: 'COL (Coil)' },
      { code: 'CON', label: 'CON (Cones)' },
      { code: 'COR', label: 'COR (Cord)' },
      { code: 'CRD', label: 'CRD (Cradle)' },
      { code: 'CSK', label: 'CSK (Cask)' },
      { code: 'CTN', label: 'CTN (Carton)' },
      { code: 'CUB', label: 'CUB (Cube)' },
      { code: 'CYL', label: 'CYL (Cylinder)' },
      { code: 'DBK', label: 'DBK (Dry Bulk)' },
      { code: 'DOC', label: 'DOC (Document)' },
      { code: 'DOZ', label: 'DOZ (Dozen)' },
      { code: 'DRK', label: 'DRK (Double Length Rack)' },
      { code: 'DRM', label: 'DRM (Drum)' },
      { code: 'DSK', label: 'DSK (Double Length Skid)' },
      { code: 'DTB', label: 'DTB (Double Length Toe Bin)' },
      { code: 'DUF', label: 'DUF (Duffel Bag)' },
      { code: 'ENV', label: 'ENV (Envelope)' },
      { code: 'FIR', label: 'FIR (Firkin)' },
      { code: 'FLO', label: 'FLO (Flo bin)' },
      { code: 'FLX', label: 'FLX (Liner Bag Liquid)' },
      { code: 'FRM', label: 'FRM (Frame)' },
      { code: 'FSK', label: 'FSK (Flask)' },
      { code: 'FTR', label: 'FTR (Flat Rack)' },
      { code: 'FWR', label: 'FWR (Forward)' },
      { code: 'GAL', label: 'GAL (Gallon)' },
      { code: 'GOH', label: 'GOH (Garments on Hangers)' },
      { code: 'GRS', label: 'GRS (Gross)' },
      { code: 'HED', label: 'HED (Heads of Beef Livestock)' },
      { code: 'HGH', label: 'HGH (Hogshead)' },
      { code: 'HMP', label: 'HMP (Hamper)' },
      { code: 'HPT', label: 'HPT (Hopper Truck)' },
      { code: 'HRB', label: 'HRB (On Hanger or Rack in Boxes)' },
      { code: 'HRK', label: 'HRK (Half Standard Rack)' },
      { code: 'HTB', label: 'HTB (Half Standard Tote Bin)' },
      { code: 'JAR', label: 'JAR (Jar)' },
      { code: 'JUG', label: 'JUG (Jug)' },
      { code: 'KEG', label: 'KEG (Keg)' },
      { code: 'KIT', label: 'KIT (Kit)' },
      { code: 'KRK', label: 'KRK (Knockdown Rack)' },
      { code: 'KTB', label: 'KTB (Knockdown Tote Bin)' },
      { code: 'LBK', label: 'LBK (Liquid Bulk)' },
      { code: 'LIF', label: 'LIF (Lifts)' },
      { code: 'LOG', label: 'LOG (Logs)' },
      { code: 'LSE', label: 'LSE (Loose)' },
      { code: 'LUG', label: 'LUG (Lugs)' },
      { code: 'LVN', label: 'LVN (Lift Van)' },
      { code: 'MIX', label: 'MIX (Mix)' },
      { code: 'MLV', label: 'MLV (MILVAN Military Van)' },
      { code: 'MPK', label: 'MPK (Multi Pack)' },
      { code: 'MRP', label: 'MRP (Multi Roll Pack)' },
      { code: 'MSV', label: 'MSV (MSCVAN Military Sealift Co...)' },
      { code: 'MXD', label: 'MXD (Mixed Type Pack)' },
      { code: 'NOL', label: 'NOL (Noil)' },
      { code: 'OVW', label: 'OVW (Overwrap)' },
      { code: 'PAI', label: 'PAI (Pail)' },
      { code: 'PAL', label: 'PAL (Pail)' },
      { code: 'PCE', label: 'PCE (Piece)' },
      { code: 'PCK', label: 'PCK (Packed not otherwise specified)' },
      { code: 'PCL', label: 'PCL (Parcel)' },
      { code: 'PCS', label: 'PCS (Pieces)' },
      { code: 'PIR', label: 'PIR (Pims)' },
      { code: 'PKG', label: 'PKG (Package)' },
      { code: 'PLF', label: 'PLF (Platform)' },
      { code: 'PLN', label: 'PLN (Pipeline)' },
      { code: 'PLT', label: 'PLT (Pallet)' },
      { code: 'POV', label: 'POV (Private Vehicle)' },
      { code: 'PRK', label: 'PRK (Pipe Rack)' },
      { code: 'QTR', label: 'QTR (Quarters of Beef)' },
      { code: 'RAL', label: 'RAL (Rail (Semiconductor))' },
      { code: 'RCK', label: 'RCK (Rack)' },
      { code: 'REL', label: 'REL (Reel)' },
      { code: 'RLL', label: 'RLL (Roll)' },
      { code: 'ROL', label: 'ROL (Roll)' },
      { code: 'RVR', label: 'RVR (Reverse Reel)' },
      { code: 'SAK', label: 'SAK (Sack)' },
      { code: 'SBC', label: 'SBC (Liner Bag Dry)' },
      { code: 'SCS', label: 'SCS (Suitcase)' },
      { code: 'SHK', label: 'SHK (Shook)' },
      { code: 'SHT', label: 'SHT (Sheet)' },
      { code: 'SID', label: 'SID (Sides of Beef)' },
      { code: 'SKD', label: 'SKD (Skid)' },
      { code: 'SKE', label: 'SKE (Skid elevating or lift truck)' },
      { code: 'SLP', label: 'SLP (Slip Sheet)' },
      { code: 'SLV', label: 'SLV (Sleeve)' },
      { code: 'SPI', label: 'SPI (Sin Cylinders)' },
      { code: 'SPL', label: 'SPL (Spool)' },
      { code: 'SVN', label: 'SVN (SEAVAN Sea Van)' },
      { code: 'TBE', label: 'TBE (Tube)' },
      { code: 'TBN', label: 'TBN (Tote Bin)' },
      { code: 'TIN', label: 'TIN (Tin)' },
      { code: 'TKR', label: 'TKR (Tank Car)' },
      { code: 'TKT', label: 'TKT (Tank Truck)' },
      { code: 'TLD', label: 'TLD (Intermodal Trainler/Container...)' },
      { code: 'TNK', label: 'TNK (Tank)' },
      { code: 'TOT', label: 'TOT (Tote)' },
      { code: 'TRC', label: 'TRC (Tierce)' },
      { code: 'TRI', label: 'TRI (Triwall Box)' },
      { code: 'TRK', label: 'TRK (Trunk or Chest)' },
      { code: 'TRY', label: 'TRY (Tray)' },
      { code: 'TSS', label: 'TSS (Trunk, Salesmen Sample)' },
      { code: 'TTC', label: 'TTC (Tote Can)' },
      { code: 'TUB', label: 'TUB (Tube)' },
      { code: 'UNP', label: 'UNP (Unpacked)' },
      { code: 'VEH', label: 'VEH (Vehicles)' },
      { code: 'VPK', label: 'VPK (Van Pack)' },
      { code: 'WDC', label: 'WDC (Wooden Case)' },
      { code: 'WHE', label: 'WHE (On Own Wheels)' },
      { code: 'WLC', label: 'WLC (Wheeled Carrier)' },
      { code: 'WRP', label: 'WRP (Wrapped)' },
      { code: 'PLT2', label: 'PLT(Pallet)' },
    ],
  },
  {
    category: 'Temperature',
    uoms: [
      { code: 'CEL', label: 'CEL (Degree Celsius)', active: true },
      { code: 'FAH', label: 'FAH (Fahrenheit)' },
    ],
  },
  {
    category: 'Unit',
    uoms: [],
  },
  {
    category: 'CBM',
    uoms: [
      { code: 'CBM', label: 'CBM', active: true },
    ],
  },
];
